spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: auth-service
              uri: ${app.routes.auth-service.uri}
              predicates:
                - Path=/api/auth/**
            - id: data-importer
              uri: ${app.routes.data-importer.uri}
              predicates:
                - Path=/api/data-importer/**
            - id: profile-service
              uri: ${app.routes.profile-service.uri}
              predicates:
                - Path=/api/profile/**
            - id: project-service
              uri: ${app.routes.project-service.uri}
              predicates:
                - Path=/api/project/**
            - id: mentor-service
              uri: ${app.routes.mentor-service.uri}
              predicates:
                - Path=/api/mentor/**
            - id: job-market-analytics-service
              uri: ${app.routes.job-market-analytics-service.uri}
              predicates:
                - Path=/api/job-market-analytics/**
            - id: telegram-bot-adapter
              uri: ${app.routes.telegram-bot-adapter.uri}
              predicates:
                - Path=/api/telegram-bot-adapter/**

app:
  http-client:
    connect-timeout: 2000
    read-timeout: 6000
  routes:
    auth-service:
      uri: ${AUTH_SERVICE_URI}
    data-importer:
      uri: ${DATA_IMPORTER_URI}
    profile-service:
      uri: ${PROFILE_SERVICE_URI}
    project-service:
      uri: ${PROJECT_SERVICE_URI}
    mentor-service:
      uri: ${MENTOR_SERVICE_URI}
    job-market-analytics-service:
      uri: ${JOB_MARKET_ANALYTICS_SERVICE_URI}


management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus

monitoring:
  prometheus:
    password: ${PROMETHEUS_PASSWORD}

jwt:
  secret: ${JWT_SECRET}
