server:
  port: 8080

app:
  routes:
    auth-service:
      uri: http://localhost:8081
    data-importer:
      uri: http://localhost:8082
    profile-service:
      uri: http://localhost:8083
    project-service:
      uri: http://localhost:8084
    mentor-service:
      uri: http://localhost:8085
    job-market-analytics-service:
      uri: http://localhost:8086
    telegram-bot-adapter:
      uri: http://localhost:8087

monitoring:
  prometheus:
    password: password

jwt:
  secret: 632eca39fc29068edc74133ca9cf8f40b4942191f80c0c78dd588835beb5f57b
